Port tests/spec/benchmarks/encode-keccak00-spec.k to Haskell backend
kframework/evm-semantics pull request #1021
Opened 2021-06-04 16:56 UTC by JKTKops

I tentatively removed this test from `tests/failing-symbolic.haskell` as well.

fixes #1011

2021-06-04 17:52 UTC, ehildenb commented on tests/specs/benchmarks/functional-spec.k
> +          </k>
```suggestion
    claim <k> runLemma(#buf(32, maxUInt256 &Int keccak(#buf(32, maxUInt256 &Int A0) ++ #buf(32, maxUInt256 &Int A1))))
           => doneLemma(#buf(32, keccak(#buf(32,A0) ++ #buf(32,A1)))) ... </k>
```

2021-06-07 14:12 UTC, ehildenb approved these changes

2021-06-07 14:28 UTC, ehildenb commented
Let's up the Jenkins timeout 20 minutes and try again with this test enabled @JKTKops .

2021-06-07 15:07 UTC, Riib11 approved these changes

2021-06-07 15:17 UTC, ehildenb requested changes
@JKTKops please remove the submodule bump to the K submodule present here. I guess you did a `git add -a`? But we should always let the auto-updater bump the submodule (see https://github.com/kframework/evm-semantics/pull/1019), because it (i) keeps the auto-updater from getting confused, and (ii) allows us to test submodule bumps in isolation and only include the changes needed to bump versions.

2021-06-07 15:46 UTC, JKTKops commented
Removed the submodule bump - yes, I did `commit -am`.

2021-06-07 15:47 UTC, ehildenb approved these changes

2021-06-07 15:54 UTC, Riib11 approved these changes

2021-06-07 17:50 UTC, merged